### ISSUE TITLE
File saving (save-buffer) broken in Emacs 25.1.1

### ISSUE THREAD

**Issue by cassiel** [overtone/emacs-live#250]
I'm getting this, and can't save files. I see the issue fix about money-patching save-buffer: I pulled the latest version and still have this problem.

![screenshot 2016-10-05 09 57 40](https://cloud.githubusercontent.com/assets/658505/19107059/5e1fc134-8ae2-11e6-8783-6b32d8844c1c.png)

**Comment by cassiel** [comment]
All seems fine in Emacs 24.x.

**Comment by dupuchba** [comment]
same here for 25.x trying with the 24.x version (mac os X)

**Comment by samaaron** [comment]
This has been fixed on master: https://github.com/overtone/emacs-live/commit/4a86f13c9f8deffec3e459de693a81437abc2a32

**Comment by piotr-yuxuan** [comment]
Hello,

Thanks for `emacs-live`, it's been a pleasure to use it! However, I'm reported the very same save error. I've cloned / pulled this repo and my local (untouched) `~/.emacs.d` is on commit [4a86f13](https://github.com/overtone/emacs-live/commit/4a86f13c9f8deffec3e459de693a81437abc2a32). I use Emacs 25.3.50 (9.0) on macOS Sierra.

I may have missed a part but it seems the bug is still here despite of the bug.

**Comment by cassiel** [comment]
Problem not fixed in the stable packs, I guess. Switching to the dev packs, both Emacs 24 and 25 break (can't find swiper?). 
![screenshot 2016-10-13 21 21 47](https://cloud.githubusercontent.com/assets/658505/19365548/2a1daa22-918b-11e6-9df4-9117e6c3a43f.jpg)

**Comment by necsoft** [comment]
+1

**Comment by samaaron** [comment]
Sorry - I have fixed this locally - and will push it up to master and make a release tomorrow :-)

**Comment by samaaron** [comment]
I've just pushed out release B24 - could you update to see if it fixes your issue? :-)

**Comment by cassiel** [comment]
Will do (when I'm on my Sierra Beta machine later today). Is this fix in the dev packs or the standard ones?

**Comment by cassiel** [comment]
OK - seems happy now in Emacs 24.x and 25.x. I do get the following (although this seems benign):

`WARNING: No org-loaddefs.el file could be found from where org.el is loaded.`
`You need to run "make" or "make autoloads" from Org lisp directory`

**Comment by rothmichaels** [comment]
> OK - seems happy now in Emacs 24.x and 25.x. I do get the following (although this seems benign):
> ````WARNING: No org-loaddefs.el file could be found from where org.el is loaded.
You need to run "make" or "make autoloads" from Org lisp directory````

This error has been logging for a long time, and is benign. *org-loaddefs.el* is loaded in  *[org-pack/init.el](https://github.com/overtone/emacs-live/blob/master/packs/dev/org-pack/init.el#L5)* so by the time `(require 'org)` is called and org-mode reports this area, `(provide 'org-loaddefs)` has already been done.

I have never investigated the difference between the included *org-loaddefs.el* and what would be generated if I ran make locally, but I have had no issues with org-mode since #243.
